spring:
  profiles:
    active: a
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workspace
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    password: password123
#    timeout: 0
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.whw.layui.dao           # 定义所有操作类的别名所在包
  mapper-locations: classpath:com/whw/layui/dao/*.xml

wx:
  appid: wx6eb1669875992729
  secret: 4a624e79f0c2ddf33e615e8452cf6929
  grant-type: authorization_code
  subscribe: 20
