spring:
  profiles:
    active: a
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.36.47:3306/workspace
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: password123
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0